### ISSUE TITLE
Haem View errors with > 1 episode

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1006]
angular.js:11598 ReferenceError: e is not defined
    at vm.getEpisodeOrdering (http://elcid-uch-test.openhealthcare.org.uk/assets/js/elcid/controllers/haem_view.js:36:29)
    at Array.<anonymous> (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17577:24)
    at comparator (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17584:36)
    at Array.sort (native)
    at http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17580:30
    at $parseFilter (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:12146:19)
    at Object.regularInterceptedExpression (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:12837:21)
    at Scope.$digest (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:14222:40)
    at Scope.$apply (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:14493:24)
    at done (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:9650:47)(anonymous function) @ angular.js:11598
3angular.js:11598 ReferenceError: e is not defined
    at vm.getEpisodeOrdering (http://elcid-uch-test.openhealthcare.org.uk/assets/js/elcid/controllers/haem_view.js:36:29)
    at Array.<anonymous> (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17577:24)
    at comparator (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17584:36)
    at Array.sort (native)
    at http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:17580:30
    at $parseFilter (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:12146:19)
    at Object.regularInterceptedExpression (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:12837:21)
    at Scope.$digest (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:14222:40)
    at Scope.$apply (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:14493:24)
    at HTMLHtmlElement.<anonymous> (http://elcid-uch-test.openhealthcare.org.uk/assets/js/bower_components/angular/angular.js:21427:23)(anonymous function) @ angular.js:11598

**Comment by GabPoll** [comment]
this is fixed.

@fredkingham a comment please from you for something that looks a bit odd - on haem view, it now shows CA from previous episodes, even for non Haem consults. Was this always the case? I think it's fine and does not need this issue to be kept open.
