### ISSUE TITLE
In FDR a bug prevents confirming diagnosis of a specific patient - ?Wider problem

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#493]
Patient Bob second patient
First on the FDR ward round
You can can't confirm his final diagnosis.
Worth checking out because risk it may occur with other patients downstream.

Mac OSX, Chrome 39

Trying to do so generates:

TypeError: Cannot read property 'default' of undefined
    at Function.flow_for_verb (http://elcid-opat.herokuapp.com/assets/js/opal/services/flow.b92516e67272.js:17:28)
    at initialize (http://elcid-opat.herokuapp.com/assets/js/elcid/controllers/diagnosis_discharge.255e58bf85f2.js:52:46)
    at new <anonymous> (http://elcid-opat.herokuapp.com/assets/js/elcid/controllers/diagnosis_discharge.255e58bf85f2.js:131:9)
    at invoke (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:3918:17)
    at Object.instantiate (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:3929:23)
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:7216:28
    at resolveSuccess (http://elcid-opat.herokuapp.com/assets/js/ui-bootstrap-tpls-0.11.0.5d1d3275f483.js:2112:32)
    at wrappedCallback (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:11498:81)
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:11584:26
    at Scope.$eval (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12608:28)angular.28f401490ec3.js:9997 (anonymous function)angular.28f401490ec3.js:7299 (anonymous function)angular.28f401490ec3.js:11501 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

**Comment by davidmiller** [comment]
This was because Bob was Followup ! Discharged.

Have updated the way we are checking to see if a patient is discharged accordingly. 

Fix deployed to elcid-test

**Comment by michaeledwardmarks** [comment]
Is fix actually deployed to elCID-OPAT?

Sent from my HTC

----- Reply message -----

**Comment by davidmiller** [comment]
FFS.

Yes - apologies - this is the second time I've typo'd that this week :(

It is indeed deployed to elcid-opat.

Good spot ! :)

On 2 January 2015 at 11:39, Michael Marks <notifications@github.com> wrote:

> Is fix actually deployed to elCID-OPAT?
>
> Sent from my HTC
>
> ----- Reply message -----
> From: "David Miller" <notifications@github.com>
> To: "openhealthcare/elcid" <elcid@noreply.github.com>
> Cc: "Marks Michael (UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDATION
> TRUST - RRV)" <michael.marks@nhs.net>
> Subject: [elcid] In FDR a bug prevents confirming diagnosis of a specific
> patient - ?Wider problem (#493)
> Date: Fri, Jan 2, 2015 11:38
>
>
> This was because Bob was Followup ! Discharged.
>
> Have updated the way we are checking to see if a patient is discharged
> accordingly.
>
> Fix deployed to elcid-test
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/openhealthcare/elcid/issues/493#issuecomment-68521196>.
>
>
> ********************************************************************************************************************
>
>
> This message may contain confidential information. If you are not the
> intended recipient please inform the
> sender that you have received the message in error before deleting it.
> Please do not disclose, copy or distribute information in this e-mail or
> take any action in reliance on its contents:
> to do so is strictly prohibited and may be unlawful.
>
> Thank you for your co-operation.
>
> NHSmail is the secure email and directory service available for all NHS
> staff in England and Scotland
> NHSmail is approved for exchanging patient data and other sensitive
> information with NHSmail and GSi recipients
> NHSmail provides an email address for your career in the NHS and can be
> accessed anywhere
>
> ********************************************************************************************************************
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/493#issuecomment-68521232>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by michaeledwardmarks** [comment]
Cool.
TO confirm - you will appear on FDR regardless of if you are discharged / discharged with follow-up / transferred / deceased?
