### ISSUE TITLE
Can't discharge Tropical or ID inpatients patients

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#515]
Very weird

- Tropical 
- ID-Inpatients
- Patients on these lists
- Discharge Link no longer works

Patients on other lists appear fine
- Immune
- Virology
- Micro
- ID Liaison fine

Heroku and UCH-Live

Wonder if related to recent bug #483

**Comment by michaeledwardmarks** [comment]
It is the same on elCID-Test but on that version Immune-Inpatients also appears to be affected which isn't I don't think on Heroku version.

**Comment by michaeledwardmarks** [comment]
Debugging the heroku version gives:

 TypeError: Cannot read property 'makeCopy' of undefined
    at new <anonymous> (http://elcid-opat.herokuapp.com/assets/js/elcid/controllers/diagnosis_discharge.b8fa19c7ac24.js:27:69)
    at invoke (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:3918:17)
    at Object.instantiate (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:3929:23)
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:7216:28
    at resolveSuccess (http://elcid-opat.herokuapp.com/assets/js/ui-bootstrap-tpls-0.11.0.5d1d3275f483.js:2112:32)
    at wrappedCallback (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:11498:81)
    at http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:11584:26
    at Scope.$eval (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12608:28)
    at Scope.$digest (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12420:31)
    at Scope.$apply (http://elcid-opat.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:12712:24)

**Comment by davidmiller** [comment]
This issue relates to:

* Patients on teams which have been selected for Discharge Diagnosis/Presenting Complaint,
* Who were added to an elCID instance before Jan 2 (https://github.com/openhealthcare/elcid/commit/eb4f0a0f902494b10ff227ed4cd16c338b6099ec)

This is fixed by this line (https://github.com/openhealthcare/elcid/blob/e55b3f4bd9a2dda3e90accbfad0296b71e8ede5f/elcid/assets/js/elcid/controllers/diagnosis_discharge.js#L24) 
 
- which should now be deployed to elcid-opat

**Comment by michaeledwardmarks** [comment]
Things I have checked:

- [ ] Patients on tropical list can be discharged
- [ ] Patients on ID-Inpatient list can be discharged
- [ ] Patients on Immune-Inpatients can be discharged
- [ ] People discharged to follow up can have discharge confirmed
- [ ] These people appear on the FDR Ward Round
- [ ] These people appear on the DLW Ward Round

This therefore appears fixed
