### ISSUE TITLE
Issues with Presenting Compaint

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#516]
Some weird behaviour here.

I save the Presenting Complaint as "Constipation"
I then re-opened it and tried to save as "Constipation and a headache"
I got an ITEM COULD NOT BE SAVED
Debugging showed

angular.28f401490ec3.js:8495 PUT http://elcid-opat.herokuapp.com/presenting_complaint/42/ 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 serverRequestangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

```python 
Traceback (most recent call last):
2015-01-15T18:43:28.979311+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
2015-01-15T18:43:28.979313+00:00 app[web.1]:     response = callback(request, *callback_args, **callback_kwargs)
2015-01-15T18:43:28.979315+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
2015-01-15T18:43:28.979317+00:00 app[web.1]:     return func(request, *args, **kwargs)
2015-01-15T18:43:28.979319+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/views/core.py", line 344, in subrecord_detail_view
2015-01-15T18:43:28.979320+00:00 app[web.1]:     subrecord.update_from_dict(data, request.user)
2015-01-15T18:43:28.979322+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/models/mixins.py", line 58, in update_from_dict
2015-01-15T18:43:28.979324+00:00 app[web.1]:     raise exceptions.APIError('Missing field (consistency_token)')
2015-01-15T18:43:28.979325+00:00 app[web.1]: APIError: Missing field (consistency_token)

```

**Comment by michaeledwardmarks** [comment]
More pressing issue is very odd.
Long description of how to replicate below because I can't explain it nor can I generate a debugging error for it.

- Add New ID-Inpatient/Tropical/Immune-Inpatient
- Complete initial modal and save
- Presenting complaint modal opens (CORRECT)
- start typing exactly this phrase "Cough and"
- once you get to "Cough a" and start typing next letter, or press space, all of a sudden the Search Hospital Number modal comes up (WEIRD and INCORRECT)
- you can escape out of that back to the Presenting Complaint modal
- you can now type more stuff without error
- but you can't use backspace to delete any of what you have already entered (BUG)
- if you use mouse to drag and select some of the text and start typing the same phrase you get the same weird search hospital number modal bug (BUG)

Bizzarrely this only happens the first time you get the Presenting Complaint Modal.
So if you just left the Presenting Complaint blank initially and clicked the button from list view you can type "Cough and a headache" with no issue.

Very strange

Debugging shows nothing during all of this!

**Comment by davidmiller** [comment]
@michaeledwardmarks I suspect what you're seeing is the manifestation of openhealthcare/opal#249 - which is a by-product of #452

**Comment by michaeledwardmarks** [comment]
You can not use backspace in Presenting Complaint!

**Comment by michaeledwardmarks** [comment]
This appears fixed to me.
I can 
- Backspace
- Open and edit existing presenting complaints
- Type stuff in the modal following add patient without any weird hospital number stuff happening
