### ISSUE TITLE
Error while advanced search

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#635]
Seen during demo: 

b.1]: Internal Server Error: /search/extract/
2015-05-08T13:06:57.446226+00:00 app[web.1]: Traceback (most recent call last):
2015-05-08T13:06:57.446229+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
2015-05-08T13:06:57.446232+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2015-05-08T13:06:57.446234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
2015-05-08T13:06:57.446236+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2015-05-08T13:06:57.446238+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
2015-05-08T13:06:57.446240+00:00 app[web.1]:     return handler(request, *args, **kwargs)
2015-05-08T13:06:57.446242+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/core/search/views.py", line 177, in post
2015-05-08T13:06:57.446244+00:00 app[web.1]:     eps = self.episodes_as_json()
2015-05-08T13:06:57.446249+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/core/search/views.py", line 160, in episodes_as_json
2015-05-08T13:06:57.446251+00:00 app[web.1]:     eps = self.get_episodes()
2015-05-08T13:06:57.446254+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/core/search/views.py", line 145, in get_episodes
2015-05-08T13:06:57.446256+00:00 app[web.1]:     all_matches = [(q['combine'], self.episodes_for_criteria(q)) for q in query]
2015-05-08T13:06:57.446258+00:00 app[web.1]:   File "/app/.heroku/src/opal/opal/core/search/views.py", line 124, in episodes_for_criteria
2015-05-08T13:06:57.446260+00:00 app[web.1]:     elif hasattr(Mod, field) and isinstance(getattr(Mod, field), fields.ForeignKeyOrFreeText):
2015-05-08T13:06:57.446262+00:00 app[web.1]: NameError: global name 'fields' is not defined

/cc @michaeledwardmarks

**Comment by davidmiller** [comment]
Seen in demo.
e.g. search on diagnosis == CAP

**Comment by michaeledwardmarks** [comment]
Fixed
