### ISSUE TITLE
Search based on Date of Referral to OPAT doesn't work

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#754]
ReferenceError: startYear is not defined
    at new PatientSummary (http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:4338:4)
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:4457:298
    at Array.map (native)
    at Function._.map._.collect (http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:4026:544)
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:4457:254
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:2400:62
    at deferred.promise.then.wrappedCallback (http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:2563:833)
    at deferred.promise.then.wrappedCallback (http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:2563:833)
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:2568:301
    at Scope.promises.$get.Scope.$eval (http://elcid04-test.herokuapp.com/assets/CACHE/js/d0ed9b0ce6c2.js:2593:1345)

**Comment by davidmiller** [comment]
Should be fixed now...

**Comment by GabPoll** [comment]
how do i reproduce / test this?

**Comment by davidmiller** [comment]
Advanced search based on date of referral ? 
Honestly you can take my word for it - it's fixed !
