### ISSUE TITLE
Injection error on elcid04-test

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#844]
-> Refer a MH patient
-> Click through to MH view

```Error: [$injector:unpr] Unknown provider: momentDateFormatFilterProvider <- momentDateFormatFilter
http://errors.angularjs.org/1.3.11/$injector/unpr?p0=momentDateFormatFilterProvider%20%3C-%20momentDateFormatFilter
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2032:8
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2224:7
    at Object.getService [as get] (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2240:122)
    at http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2224:232
    at Object.getService [as get] (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2240:122)
    at null.$filter (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2766:106)
    at Parser.filter (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2596:52)
    at Parser.filterChain (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2595:122)
    at Parser.statements (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2594:22)
    at Parser.parse (http://elcid04-test.herokuapp.com/assets/CACHE/js/a93f9c3a0fc5.js:2584:302) <div class="outer-container ng-scope" ng-view="" autoscroll="true" ng-hide="ready==false">(anonymous function) @ a93f9c3a0fc5.js:2564```

**Comment by davidmiller** [comment]
Fixed !
